Prop-House/prop-house-monorepo

packages/prop-house-webapp/src/components/RoundCard/RoundCard.module.css

dark bg for ended round cards

---

packages/prop-house-webapp/src/components/pages/Home/index.tsx

Sorts the community cards in home page by `.ethFunded`

Sort communities in home page

---

packages/prop-house-webapp/src/components/HomeHeader/index.tsx

When a user command & clicks the homepage "learn more" button we should open the page in a new tab.

Open homepage faq button in new tab if command plus clicked

---

packages/prop-house-webapp/src/components/HomeHeader/index.tsx

Add i18n var to homepage 'learn more' button

---

packages/prop-house-backend/src/entities/signed.pipe.ts
packages/prop-house-backend/src/vote/votes.controller.ts

- Adds signer validation to signature validation pipe
- Adds `SignedPayloadValidationPipe` back to vote creation route
- Adds checks against weight so as to make sure that attempted vote + previous votes don't exceed total voting power
- Adds check for signed payload community address so as to make sure that voting power is being requested from the expected community.

Fix voting

---

packages/prop-house-backend/src/vote/votes.controller.ts

- Fix issues with potential voting looholes

Additioanl fixes for voting checks

---

packages/prop-house-webapp/src/components/pages/Create/index.tsx

When the round was being fetch on the `/create` page we had the word `Loading...` displayed. Now, we're swapping it out for our general purpose `<LoadingIndicator />` component.

Change the word 'loading...' to the <LoadingIndicator /> component

---

packages/prop-house-webapp/src/components/RoundContent/index.tsx
packages/prop-house-webapp/src/components/SuccessModal/index.tsx
packages/prop-house-webapp/src/components/VotesVerificationModal/VotesVerificationModal.module.css
packages/prop-house-webapp/src/components/VotesVerificationModal/index.tsx
packages/prop-house-wrapper/src/builders.ts

Adds signifiers to let the user know the state of their votes if from gnosis:
- On successfully initiating the vote
- In the votes verification modal

Add FE signifiers

---

packages/prop-house-webapp/src/components/RoundUtilityBar/RoundUtilityBar.module.css
packages/prop-house-webapp/src/components/RoundUtilityBar/index.tsx

Add snapshot block to round utility bar

---

packages/prop-house-backend/src/db/migrations/1668543942977-AddBlockHeightSetDefaultFundingAmount.ts
packages/prop-house-backend/src/proposal/proposal.entity.ts
packages/prop-house-backend/src/vote/vote.entity.ts
packages/prop-house-backend/src/vote/vote.types.ts
packages/prop-house-backend/src/vote/votes.controller.ts
packages/prop-house-backend/src/vote/votes.service.ts
packages/prop-house-webapp/src/components/RoundContent/index.tsx
packages/prop-house-wrapper/src/builders.ts
packages/prop-house-wrapper/src/index.ts

- Fixes bug where non validated votes where being counted as valid
- Add replay prevention
- Removes `signatureState` from payload to be signed

Vote security & fixes

---

packages/prop-house-webapp/src/components/HouseHeader/HouseHeader.module.css
packages/prop-house-webapp/src/components/HouseHeader/index.tsx

Update house page mobile UI

---

packages/prop-house-webapp/src/components/RoundContent/index.tsx
packages/prop-house-webapp/src/components/SortToggles/index.tsx
packages/prop-house-webapp/src/components/pages/House/index.tsx
packages/prop-house-webapp/src/components/pages/Round/index.tsx

- House page now defaults to "all rounds" as opposed to "active"
- Round page when in voting now defaults to "sort by votes"

Small UX improvements

---

packages/prop-house-webapp/src/components/NoActiveHouseModal/NoActiveHouseModal.module.css
packages/prop-house-webapp/src/components/NoActiveHouseModal/index.tsx
packages/prop-house-webapp/src/components/ProtectedRoute/ProtectedRoute.tsx

Update the modal styles & copy to match all our other new modals.

New modal for No Active House route

---

packages/prop-house-webapp/src/components/PropCardVotingModule/index.tsx
packages/prop-house-webapp/src/components/ProposalCard/index.tsx
packages/prop-house-webapp/src/components/ProposalModal/index.tsx
packages/prop-house-webapp/src/components/ProposalModalFooter/index.tsx
packages/prop-house-webapp/src/components/ProposalModalHeader/index.tsx
packages/prop-house-webapp/src/components/RoundContent/index.tsx
packages/prop-house-webapp/src/components/VoteAllotmentTooltip/index.tsx
packages/prop-house-webapp/src/components/pages/Round/index.tsx
packages/prop-house-webapp/src/state/slices/propHouse.ts
packages/prop-house-webapp/src/utils/refreshActiveProposal.ts

- refactors prop modal state management to use redux store
- adds up/down keyboard voting

Refactor prop modal state management

---

packages/prop-house-webapp/src/components/ProposalContent/index.tsx
packages/prop-house-webapp/src/css/globals.css

New base styles for Editor content & Proposal copy

New Proposal Copy styles

---

packages/prop-house-webapp/src/components/StatusFilters/index.tsx

We had a missing i18n variable, added it back in.

Hotfix: Add translation variable

---

packages/prop-house-webapp/src/App.css
packages/prop-house-webapp/src/App.tsx
packages/prop-house-webapp/src/components/LocaleSwitcher/LocaleSwitcher.module.css
packages/prop-house-webapp/src/components/ProposalEditor/ProposalEditor.module.css
packages/prop-house-webapp/src/components/ProposalEditor/index.tsx
packages/prop-house-webapp/src/components/pages/Create/Create.module.css
packages/prop-house-webapp/src/components/pages/Create/index.tsx
packages/prop-house-webapp/src/components/pages/FAQ/index.tsx
packages/prop-house-webapp/src/quill.css
packages/prop-house-webapp/src/utils/bgColorForFooter.ts
packages/prop-house-webapp/src/utils/bgColorForPage.ts

Update the Create page styles to be more in line with the rest of the site.

Update Create page styles

---

packages/prop-house-webapp/src/components/HouseHeader/index.tsx
packages/prop-house-webapp/src/components/ReadMore/ReadMore.module.css
packages/prop-house-webapp/src/components/ReadMore/index.tsx
packages/prop-house-webapp/src/components/RoundHeader/index.tsx

This PR adds back in line breaks for the house & round description, conditionally shows "Read More" button only when necessary, and changes the line clamping from 3 lines to 4.

Fix House & Round Descriptions

---

packages/prop-house-backend/src/proposal/proposals.controller.ts
packages/prop-house-wrapper/example/example.ts
packages/prop-house-wrapper/src/index.ts
packages/prop-house-wrapper/src/types/eip712Types.ts

This creates new eip712 types for the Update and Delete actions for proposals. It also uses the signed payload for verification.

Correct types and wrapper for PATCH/DELETE

---

packages/prop-house-webapp/src/components/RoundModules/index.tsx

Found an issue when going from editing a proposal to then creating a new proposal. When a user clicks "Edit" we're setting the proposals fields in our data object. Whether we edit or not (lets say we just hit cancel and don't update the proposal), if you then go to "Create New Proposal" from the round page, it will pre-load the fields with the last prop we were just editing. 
You fix this by dispathcing a `clearProposal()` call and we already fixed this when clicking the "+ New Prop" button from the Prop Modal footer (see here: https://github.com/Prop-House/prop-house-monorepo/pull/344/commits/1114109c52ba1f2679eda1394f5b888b65429e27) and all we're doing now is dispatching it from the round page's "Create New Proposal" button as well since there's two avenues to create props from.

Hotfix: Clear proposal data

---

packages/prop-house-communities/src/communities/index.ts
packages/prop-house-communities/src/strategies/index.ts
packages/prop-house-communities/src/strategies/onchainMonkey.ts
packages/prop-house-communities/test/onchainMonkey.test.ts

Creates new voting strategy for the OCM community that follows the rule: `X + Y + min(X,Y)`

Add custom OCM voting strategy

---

packages/prop-house-webapp/package.json
packages/prop-house-webapp/src/components/Divider/Divider.module.css
packages/prop-house-webapp/src/components/Divider/index.tsx
packages/prop-house-webapp/src/components/ProposalCard/ProposalCard.module.css
packages/prop-house-webapp/src/components/ProposalCard/index.tsx
packages/prop-house-webapp/src/types/is-image-url.d.ts
packages/prop-house-webapp/src/utils/getImageFromDescription.ts
yarn.lock

If a proposal has an image we'll display it on the prop card itself. Note, if the image url is invalid it won't show the image.

Add image to Prop Card

---

packages/prop-house-webapp/src/components/VoteAllotmentModal/VoteAllotmentModal.module.css
packages/prop-house-webapp/src/components/VoteConfirmationModal/VoteConfirmationModal.module.css
packages/prop-house-webapp/src/components/VoteConfirmationModal/index.tsx

Set max height height for vote confirmation container

---

packages/prop-house-webapp/src/pages/Proposal/index.tsx

Verify: https://deploy-preview-428--prop-house.netlify.app/proposal/1562

Add container to Proposal page

---

packages/prop-house-webapp/src/App.tsx

the OpenGraph cards weren't wrapped in <WagmiClient />
Verify: https://deploy-preview-429--prop-house.netlify.app/proposal/1488/card

Wrap App Wagmi client

---

packages/prop-house-webapp/src/App.tsx

Reverts Prop-House/prop-house-monorepo#429

Revert "Wrap App Wagmi client"

---

packages/prop-house-webapp/src/App.tsx

Verify: https://deploy-preview-432--prop-house.netlify.app/proposal/1561/card

Wrap Entire App in WagmiClient

---

packages/prop-house-webapp/src/components/CommunityCard/CommunityCard.module.css
packages/prop-house-webapp/src/components/RenderedProposalFields/RenderedProposalFields.module.css
packages/prop-house-webapp/src/components/RenderedProposalFields/index.tsx
packages/prop-house-webapp/src/pages/Proposal/Proposal.module.css
packages/prop-house-webapp/src/pages/Proposal/index.tsx

Promote master to prod

---

packages/prop-house-communities/src/communities/index.ts
packages/prop-house-communities/src/strategies/index.ts
packages/prop-house-communities/src/strategies/perWalletVoteErc20.ts

Adds voting strategies for the following communities:
- Rug Radio
- Headline
- Mferbuilder
- Nouns OTG
And a new voting strat: `perWalletVoteErc20`

Add voting strategies

---

packages/prop-house-communities/src/communities/index.ts
packages/prop-house-webapp/src/components/RoundCard/index.tsx
packages/prop-house-webapp/src/components/RoundUtilityBar/index.tsx
packages/prop-house-webapp/src/utils/countDecimals.ts

http://prop.house/index-card/nounish-is...

Display up to 3 decimals

---

packages/prop-house-webapp/src/components/Banner/Banner.module.css
packages/prop-house-webapp/src/components/Banner/index.tsx

Update banner font

---

packages/prop-house-webapp/src/App.tsx
packages/prop-house-webapp/src/components/Banner/index.tsx

- Removes hackweek banner
- Makes Banner reusable

Remove hackweek banner

---

packages/prop-house-webapp/src/components/ReplyBar/index.tsx
packages/prop-house-webapp/src/components/RoundContent/index.tsx
packages/prop-house-webapp/src/components/VoteConfirmationModal/index.tsx

Fixed bugs found in inf round UX: 
- Prop A comments appearing in prop B
- Scrolling issues
- React warnings
- Remove erroneous copy

Inf round bug fixing

---

packages/prop-house-backend/src/proposal/proposals.controller.ts
packages/prop-house-backend/src/utils/execStrategy.ts
packages/prop-house-communities/src/_strategies/balanceOfErc20.ts
packages/prop-house-communities/src/_strategies/balanceOfErc721.ts
packages/prop-house-communities/src/_strategies/fixedNum.ts
packages/prop-house-communities/src/_strategies/index.ts
packages/prop-house-communities/src/_strategies/validEnsAndMinBal.ts
packages/prop-house-communities/src/actions/execStrategy.ts
packages/prop-house-communities/src/types/_Strategy.ts
packages/prop-house-communities/src/utils/getStrategy.ts
packages/prop-house-webapp/src/components/AcceptingPropsModule/index.tsx
packages/prop-house-webapp/src/components/ProposalWindowButtons/index.tsx
packages/prop-house-webapp/src/components/StatusRoundCard/index.tsx
packages/prop-house-webapp/src/hooks/useProposalGrants.ts
packages/prop-house-webapp/src/hooks/useVotingPower.ts
packages/prop-house-webapp/yarn.lock

This PR refactors some typing and strategy selection in the `prop-house-communties` package as well as refactoring some of the webapp "can propose" and "voting power" logic into hooks for reusability.

oc-summer tweaks

---

packages/prop-house-backend/package.json
packages/prop-house-backend/src/app.controller.ts
packages/prop-house-backend/src/app.module.ts
packages/prop-house-backend/src/config/configuration.ts
packages/prop-house-backend/src/discord/discord.controller.ts
packages/prop-house-backend/src/discord/discord.module.ts
packages/prop-house-backend/src/discord/discord.service.spec.ts
packages/prop-house-backend/src/discord/discord.service.ts
packages/prop-house-backend/src/proposal/proposals.controller.ts
packages/prop-house-backend/src/proposal/proposals.service.ts
packages/prop-house-backend/tsconfig.json
yarn.lock

This adds a basic admin bot for fetching information about proposals with `/getprop <id>` and addressing spam proposals via `/deleteprop <id>`. Proposals that are "deleted" are marked as soft-deleted and can be restored as needed.

Basic Discord Admin Bot

---

packages/prop-house-backend/package.json
packages/prop-house-communities/package.json
packages/prop-house-communities/src/actions/getRelevantComms.ts
packages/prop-house-webapp/package.json
packages/prop-house-webapp/src/App.tsx
packages/prop-house-webapp/src/components/ImageUploadModal/index.tsx
packages/prop-house-webapp/src/components/OpenGraphHouseCard/index.tsx
packages/prop-house-webapp/src/components/OpenGraphRoundCard/index.tsx
packages/prop-house-webapp/src/components/ProposalEditor/index.tsx
packages/prop-house-webapp/src/components/ProposalInputs/index.tsx
packages/prop-house-webapp/src/components/ProposalModal/index.tsx
packages/prop-house-webapp/src/components/ReplyBar/index.tsx
packages/prop-house-webapp/src/components/RoundContent/index.tsx
packages/prop-house-webapp/src/components/SaveProposalModal/index.tsx
packages/prop-house-webapp/src/hooks/useEthersSigner.ts
packages/prop-house-webapp/src/pages/Create/index.tsx
packages/prop-house-webapp/src/pages/Home/index.tsx
packages/prop-house-webapp/src/pages/House/index.tsx
packages/prop-house-webapp/src/pages/Proposal/index.tsx
packages/prop-house-webapp/src/pages/Round/index.tsx
packages/prop-house-webapp/src/pages/Upload/index.tsx
packages/prop-house-wrapper/package.json
yarn.lock

- Downgrades backend/community/wrapper packages to their old ts versions
- Uses [ethers adapter](https://wagmi.sh/react/ethers-adapters#wallet-client--signer) on webapp to instantiate wrapper

Downgrade ts & adapt viem/ethers

---

packages/prop-house-communities/src/_strategies/index.ts
packages/prop-house-communities/src/_strategies/minimumBalance.ts

Adds a simple minimum balance strategy

Add min bal strategy

---

packages/prop-house-webapp/src/components/JumboRoundCard/index.tsx
packages/prop-house-webapp/src/components/RoundsFeed/index.tsx
packages/prop-house-webapp/src/hooks/useRoundsFilter.ts
packages/prop-house-webapp/src/utils/fetchRoundsForFilter.ts
packages/prop-house-webapp/src/utils/supabaseModeration.ts

- Adds featured rounds to be managed via supabase
- Adds Proposing and Voting filters

Add featured rounds + new filters
