packages/prop-house-webapp/src/components/RoundCard/index.tsx

1) Render markdown in the Round cards correctly
2) Disable link click on from this screen to prevent the link being clicked in the copy vs the Round card itself

render markdown in round card description, but disable links when clicking the card

---

packages/prop-house-webapp/src/App.css

Sticky elements (house utility bar + round modules) stopped working due to adding the `overflow` property on the `div.wrapper` that wraps the entire app (found in `App.tsx`). removing it to allow child elements that use the css `sticky` property to function correctly.
eg: current deployment in prod does not have sticky house utility bar or round modules. the fix allows for 👇

Fix sticky elements issue

---

packages/prop-house-webapp/src/components/RenderedProposalFields/RenderedProposalFields.module.css
packages/prop-house-webapp/src/components/RenderedProposalFields/index.tsx
packages/prop-house-webapp/src/components/pages/Proposal/Proposal.module.css
packages/prop-house-webapp/src/components/pages/Proposal/index.tsx
packages/prop-house-webapp/src/utils/bgColorForFooter.ts
packages/prop-house-webapp/src/utils/bgColorForPage.ts

- back button displays the House's Round you're navigating back to next to it
- the proposer address changed to pink
- background color changed to gray
- titles change from gray to black
- replaces #241

Update Proposal Page Colors And Back Button

---

packages/prop-house-webapp/src/components/pages/House/index.tsx
packages/prop-house-webapp/src/components/pages/Round/index.tsx
packages/prop-house-webapp/src/utils/markdownToPlainText.ts

Turn markdown being displayed in descriptions to plain text:

Parse markdown descriptions to plain text in og cards

---

packages/prop-house-webapp/src/components/ProposalCard/ProposalCard.module.css
packages/prop-house-webapp/src/components/ProposalCard/index.tsx

We are hiding the date on mobile to prevent overflow cause by a combination of very long ENS names and timestamps. We are already doing this with the cards during Voting status, and now were adding the rule during the Accetpting Props status

Hide date on mobile during proposal round on top of voting

---

packages/prop-house-webapp/src/components/RenderedProposalFields/RenderedProposalFields.module.css
packages/prop-house-webapp/src/components/RenderedProposalFields/index.tsx

Added a class to target the entire proposal body. Now links (a tags) will be pink and bolded. On hover they'll be underlined like we do in House/Round descriptions. This supports both markdown links and the rich text editor link embeds.

Add UI highlighting to links in the proposal body

---

packages/prop-house-webapp/src/components/HomeStats/index.tsx

On the homepage stats section, if there's only 1 round create or 1 prop submitted we should use the singular version of the word.

Handle singular round and prop stats

---

packages/prop-house-webapp/src/components/HouseUtilityBar/index.tsx

If there's either a `Voting` or `Proposing` round, the default filter is `Active`. However, if a user inputs something in the search bar, we want to filter via all rounds available. Therefore, when typing, if the status filter is `Active` let's change it to `All Rounds` to reflect in the UI what's going in the logic.

During round search, if the filter is set to Active, change it to All Rounds

---

packages/prop-house-webapp/src/components/LocaleSwitcher/index.tsx
packages/prop-house-webapp/src/components/NavBar/index.tsx

When the mobile pop-out menu is open, it would stay open even after a selection was made. Now, if you click a nav item it will close the menu. Also, if you change the selected langauge it will close the menu.

Close mobile nav when selection a nav button

---

packages/prop-house-webapp/src/components/RoundCard/index.tsx

We were seeing HTML tags in the round's description of the Round card on the House page. Switched from `React Markdown` package to a `Markdown-to-JSX` one that can handle both Markdown and HTML rendering.
We are overriding (meaning changing) the title tags (`h1,  h2, h3`) to regular `<p>` tags so that we're not displaying big titles on our limited-sized card. Also, in this PR we're converating `<a>` tags to `<span>`'s, as mentioned in #251 and we're also overriding `<br>` tags to disallow extra spacing on the card TLDRs. We expect a card's TLDR to read as if it were one paragraph.

Handle HTML in round's description on round card

---

packages/prop-house-webapp/src/components/RoundUtilityBar/index.tsx

Add a space funding amount number and the currency type text next to it.

Add a space between funding amount and currency type in round utility bar

---

packages/prop-house-webapp/src/components/PropStats/index.tsx

In the `UserPropCard` module there's a component called `PropStats` that gives a builder some info about their standing in a funding round. If they have a proposal that is **not** in the winning group then a calculation is performed (`votesNeededToWin` function) to get the minimum number of votes needed to bump their proposal into the winning batch. 
The issue was that we were returning `NaN` (not a number) for this, and it's because the property used was `prop.score` where it should have been `prop.voteCount`. This has been updated and now works as intended.

Fix NaN issue for calculating "Votes Needed"

---

packages/prop-house-webapp/src/components/EthAddress/index.tsx
packages/prop-house-webapp/src/components/ProposalCard/index.tsx

There's a repeating avatar image bug with the `Davatar` npm package, and until we figure out what's causing it we should remove it from the UI.

Hide Davatar on proposal cards

---

packages/prop-house-backend/src/auction/auction.entity.ts
packages/prop-house-backend/src/db/migrations/1666111078154-UpdateFundingAmountPropertyType.ts
packages/prop-house-webapp/src/components/RoundCard/RoundCard.module.css
packages/prop-house-webapp/src/components/RoundCard/index.tsx
packages/prop-house-webapp/src/components/RoundUtilityBar/index.tsx
packages/prop-house-webapp/src/components/TruncateThousands/index.tsx

Various rounds are going to be needing decimal points for their award `fundingAmount`. This PR updates the type for the property as well as adds display when needed within the web app.

Add decimal support

---

packages/prop-house-webapp/src/css/globals.css
packages/prop-house-webapp/src/quill.css

Our modals were slightly below center before, now we've added some CSS to align them horizontally & vertically.

Center modals on screen

---

packages/prop-house-webapp/src/utils/sortRoundByStatus.ts

We were originally sorting Ended rounds by the rounds creation date. However, sometimes we create rounds very early in preparation for it but that means rounds that go live after it will be sorted after it, even if said original round actually goes live later. So we fixed this by sorting the Ended rounds by the round's start time.

Sort ended rounds by start time

---

packages/prop-house-webapp/src/components/RoundCard/RoundCard.module.css

With the addition of funding amounts with decimals, the info becomes pretty long so on mobile (450px breakpoint) we hide the `# of proposals` section (previously hidden at 375px) to allow for more room.

Increase breakpoint width for hiding section on round card

---

packages/prop-house-webapp/src/components/OpenGraphRoundCard/index.tsx

With the addition of rounds with funding amounts with decimals (ie. 0.5, 1.25, etc), the amount was being passed into the `TruncateThousands` component which will round to the nearest whole number (ie. 0.25 becomes 0 and 0.5 becomes 1) unless we pass in a `decimals` prop. Added support for 2 decimal places here and is working as intended.

Support 2 decimal places for round's OpenGraph card funding amount

---

packages/prop-house-webapp/src/components/TruncateThousands/index.tsx

When the stat is 4-digits or more we truncate the number. This commit adds back in the letter 'K' after a truncated number. There's also fix to be inclusive of the number 1000 when checking for truncation.

Add 'K' to truncated homepage stats

---

packages/prop-house-webapp/src/components/HouseHeader/index.tsx

UI bug that displays nothing if there's either zero proposals or zero round on a House. We should show the number 0 instead of nothing.

Add 0 if there's no proposals or rounds

---

packages/prop-house-webapp/src/components/OpenGraphHouseCard/index.tsx

When a new house is created there have been no rounds created, proposals submitted, or currency distributed. Since these values are `null`, in the social sharing card we were seeing "nothing" where we _should_ have been display `0` to the user. This PR checks for null values & displays a `0` if `null` is returned.

Null check in House sharing card

---

packages/prop-house-webapp/src/components/OpenGraphHouseCard/index.tsx

1) use the new `getHouseCurrency` util func to return correct currency type for social sharing cards (ie. APE/ UMA/ETH)
2) swap order of currency type & currency amount

Support various currency types for House's social sharing card

---

packages/prop-house-webapp/package.json
packages/prop-house-webapp/src/utils/communitySlugs.ts
yarn.lock

When rounds have colons (ie. `Open Round: 12`), building url slugs get messed up when you're opening them in a new tab. This PR removes them so the slugs are `prop.house/nouns/open-round-12` vs`prop.house/nouns/open-round:-12`

Remove colons from url slugs

---

packages/prop-house-webapp/src/components/CommunityProfImg/CommunityProfImg.module.css

To better support PNGs, i've added a white background to the image to prevent seeing through to the background.

Add white background to House image

---

packages/prop-house-webapp/src/components/pages/Home/index.tsx

The homepage statistic for "ETH Funded" was including non-ETH currencies as well, conflating the number. By filtering out UMA & Meebits houses from this number we get a better picture of actual ETH deployed. This is a temporary fix while we wait for the `community` object to be updated with more `currency` values.

Filter out non-ETH houses from homepage 'ETH Funded' stat

---

packages/prop-house-webapp/src/utils/communitySlugs.ts

Removing colons from slugs doesn't work when the round is the entry point (it breaks in the`getAuctionWithNameForCommunity` call). Reverting until another solution is found.

Revert slugify

---

packages/prop-house-webapp/src/components/RoundContent/index.tsx

`useDapp` is causing issues where metamask throws error when trying to fetch votes. This hot fix uses our default provider for fetching votes.

Hot fix: Use default provider to fetch votes

---

packages/prop-house-webapp/src/components/HouseHeader/index.tsx

When there's only one round we were still seeing the use of the plural "Rounds" due to a conditional looking for a Number but getting back String.

Type corercion for number of rounds

---

packages/prop-house-webapp/src/components/RoundUtilityBar/RoundUtilityBar.module.css
packages/prop-house-webapp/src/components/RoundUtilityBar/index.tsx

Now that we have a new item (`Snapshot`), it takes up more real estate and the breakpoints were off, causing overflow UI on medium to small screens. This PR updates the breakpoints to show/hide content in the Round utility bar.

Fix overflow columns on round utility bar

---

packages/prop-house-webapp/src/components/RoundContent/index.tsx
packages/prop-house-webapp/src/utils/aggVoteWeight.ts

This PR updates the remaining vote calculation to only deduct **validated** votes. Votes that are pending validation or have failed validation should be disregarded.

Remaining Vote Calculation Bug Fix

---

packages/prop-house-webapp/src/components/ProposalCard/ProposalCard.module.css
packages/prop-house-webapp/src/utils/getWinningIds.ts

This PR updates how we handle ties. If there's a tie between proposals, the earliest submitted proposal wins.

Sort winning props that tie by created date

---

packages/prop-house-webapp/src/components/Button/Button.module.css
packages/prop-house-webapp/src/components/PropCardsAndModules/index.tsx
packages/prop-house-webapp/src/components/ProposalCard/ProposalCard.module.css
packages/prop-house-webapp/src/components/ProposalCard/index.tsx
packages/prop-house-webapp/src/components/ProposalHeaderAndBody/index.tsx
packages/prop-house-webapp/src/components/ProposalModal/index.tsx
packages/prop-house-webapp/src/components/ProposalModalFooter/ProposalModalFooter.module.css
packages/prop-house-webapp/src/components/ProposalModalFooter/index.tsx
packages/prop-house-webapp/src/components/ProposalModalHeader/ProposalModalHeader.module.css
packages/prop-house-webapp/src/components/ProposalModalHeader/index.tsx
packages/prop-house-webapp/src/components/ProposalModalNavButtons/ProposalModalNavButtons.module.css
packages/prop-house-webapp/src/components/ProposalModalNavButtons/index.tsx
packages/prop-house-webapp/src/components/ProposalModalVotingModule/ProposalModalVotingModule.module.css
packages/prop-house-webapp/src/components/ProposalModalVotingModule/index.tsx
packages/prop-house-webapp/src/components/RoundContent/index.tsx
packages/prop-house-webapp/src/components/RoundOverModule/index.tsx
packages/prop-house-webapp/src/components/VotesDisplay/VotesDisplay.module.css
packages/prop-house-webapp/src/css/globals.css
packages/prop-house-webapp/src/utils/getWinningIds.ts

Winning Proposals UI

---

packages/prop-house-webapp/src/components/StatusPill/StatusPill.module.css

If the Round title is long and pushed against a "Not Started" status pill it made the words break to two lines. By setting the minimum width of the text to the max content of said copy we prevent the line-break within the pill.

Prevent line break within status pill

---

packages/prop-house-backend/src/db/migrations/1670995397176-ProposalSoftDelete.ts
packages/prop-house-backend/src/proposal/proposal.entity.ts
packages/prop-house-backend/src/proposal/proposal.types.ts
packages/prop-house-backend/src/proposal/proposals.controller.ts
packages/prop-house-backend/src/utils/date.ts
packages/prop-house-wrapper/src/builders.ts
packages/prop-house-wrapper/src/index.ts

This PR adds support for PATCH and DELETE verbs to the `/proposals` endpoint in order to support users being able to delete or update their proposals.
This endpoint requires a body that matches [UpateProposalDto](https://github.com/Prop-House/prop-house-monorepo/blob/carrot-prop-patch/packages/prop-house-backend/src/proposal/proposal.types.ts#L32-L35) and is signed by the author.
This endpoint requires a body that matches [DeleteProposalDto](https://github.com/Prop-House/prop-house-monorepo/blob/carrot-prop-patch/packages/prop-house-backend/src/proposal/proposal.types.ts#L37-L40) and is signed by the proposal author. This differs from a more normal `DELETE /proposals/:id` path because the proposal ID must be part of the payload that is being signed and having the ID in two locations …

Add ability to PATCH and DELETE Proposals

---

packages/prop-house-webapp/src/components/ProposalSuccessModal/ProposalSuccessModal.module.css

If there's an incredibly long ENS address we should truncate it and use ellipsis

Hotfix: Truncate long ENS

---

packages/prop-house-webapp/src/components/ReadMore/ReadMore.module.css

The clickable area of the "Read More" button was the full-width of the page. We should restrict this to the width of the word's themselves. Top was before, bottom is after.

Shorten clickable area to button length

---

packages/prop-house-webapp/src/components/ForceOpenInNewTab/index.tsx
packages/prop-house-webapp/src/components/HouseHeader/index.tsx
packages/prop-house-webapp/src/components/RoundHeader/index.tsx
packages/prop-house-webapp/src/components/pages/Create/index.tsx
packages/prop-house-webapp/src/utils/isLongName.ts
packages/prop-house-webapp/src/utils/isValidPropData.ts

Moving some reused code to their own utility functions and one component, declared in two places, to a reusable component. Also this component had the same name as a utility function so I renamed it in the process as well.

Extract code to util funcs

---

packages/prop-house-backend/src/community/community.service.ts
packages/prop-house-webapp/src/components/pages/Home/index.tsx

When aggregating data on communities, filter out any `auction` whose primary funding currency (`currencyType`) does not contain `ETH`.

Filter for ETH

---

packages/prop-house-backend/src/community/community.service.ts
packages/prop-house-webapp/src/components/CommunityCard/index.tsx
packages/prop-house-webapp/src/components/OpenGraphHouseCard/index.tsx
packages/prop-house-webapp/src/components/pages/Home/index.tsx
packages/prop-house-wrapper/src/builders.ts

- Adds `totalFunded` as community property to complement `ethFunded` as some communities use alternative currencies
- Sorts home page communities by number of proposals

Hot fix: Add total funded 

---

packages/prop-house-webapp/src/components/AdminTool/AdminTool.module.css
packages/prop-house-webapp/src/components/AdminTool/index.tsx
packages/prop-house-webapp/src/components/DevEnvDropdown/DevEnvDropdown.module.css
packages/prop-house-webapp/src/components/DevEnvDropdown/index.tsx
packages/prop-house-webapp/src/components/NavBar/index.tsx
packages/prop-house-webapp/src/state/slices/configuration.ts

- Adds dropdown to switch between different backend hosts for easier development. 
- Shows diff options depending on env (localhost, dev and prod on local / dev & prod on previews)
- Does not display switcher on prod

Add host switcher

---

packages/prop-house-webapp/src/utils/getWinningIds.ts

When a round enters the voting stage technically there are "winners" tied for first place (ie earliest submitted x-number of props). We shouldn't show a crown if the prop has zero votes.
Below you can see that even though we will have 5 winners, we won't show a crown until a prop has at least 1 vote.

Don't show crown if prop has zero votes

---

packages/prop-house-webapp/src/components/NotFound/NotFound.module.css
packages/prop-house-webapp/src/pages/House/index.tsx
packages/prop-house-webapp/src/pages/Round/Round.module.css
packages/prop-house-webapp/src/pages/Round/index.tsx

Redid the loading logic for the House & Round pages that would cause the "No Rounds available" message to prematurely display while fetching.

Add loaders on House & Round pages 

---

packages/prop-house-backend/src/proposal/proposal.resolver.ts
packages/prop-house-backend/src/proposal/proposals.service.ts

This adds the `proposalsBetween` query which will allow users to find proposals that were created between specified dates.

Add proposalsBetween query

---

packages/prop-house-webapp/src/components/ProposalCard/ProposalCard.module.css
packages/prop-house-webapp/src/components/ProposalCard/index.tsx
packages/prop-house-webapp/src/components/ProposalModalHeader/ProposalModalHeader.module.css

This PR cleans up prop display on mobile:
- Displays title + image only on prop card (no more tldrs)
- Expand prop title when displaying prop modal to two lines (as opposed to current one line)

Clean up prop display on mobile

---

packages/prop-house-webapp/src/components/RenderedProposalFields/RenderedProposalFields.module.css
packages/prop-house-webapp/src/components/RenderedProposalFields/index.tsx
packages/prop-house-webapp/src/pages/Proposal/Proposal.module.css
packages/prop-house-webapp/src/pages/Proposal/index.tsx

When landing directly onto a prop page, the back button was linking to the proposal's house, not the round. This PR correct the back button link to direct the user to the round and makes a few modifications on how it is displayed.
Before
After

Fix back btn

---

packages/prop-house-webapp/src/components/RoundModules/index.tsx
packages/prop-house-webapp/src/components/VotingModule/VotingModule.module.css
packages/prop-house-webapp/src/components/VotingModule/index.tsx

Problem: 
We were using house name as the token name required to vote. Some houses have differing names to their tokens (eg Nouns short shorts using Nouns token).
Solution:
Displays corresponding token name using the `community.contractAddress`, defaults to trimmed address if no name is found.

Display appropriate token name

---

packages/prop-house-webapp/src/components/OpenGraphProposalCard/index.tsx
packages/prop-house-webapp/src/components/ProposalCard/index.tsx
packages/prop-house-webapp/src/components/ProposalContent/index.tsx

Pinata requires a crossOrigin tag to be set in order for host restriction to work. https://docs.pinata.cloud/gateways/gateway-access-controls

Pinata requires anonymous cross origin

---

packages/prop-house-webapp/src/components/RenderedProposalFields/index.tsx

The previous hotfix missed the Proposal page which uses a separate component than the proposal card. This hotfix addresses the Proposal page.

Add img tag injection on proposal page

---

packages/prop-house-protocol/contracts/ethereum/rounds/InfiniteRound.sol

Previously, we were only writing the output of `max(passed_start_timestamp, current_block_timestamp)` to the `startTimestamp` state variable. The value that was passed to Starknet could still be less than the current block timestamp. This could allow round creators to use past snapshots, or result in the round failing to deploy on Starknet if `0` was provided.
The fix is to write the output of `max` to `config.startTimestamp`.

Fix Infinite Round Past Start Timestamp Bug

---

packages/prop-house-backend/src/discord/discord.module.ts
packages/prop-house-backend/src/discord/discord.service.ts

This PR will consume generalized `prop-admin-<community id>` roles rather than only a single admin. This also adds the `prop-superadmin` role which can manage all houses.

Discord Bot Admin Expansion

---

packages/prop-house-backend/package.json
yarn.lock

Another package had its ts-node bumped but the monorepo structure yielded both 10.0 and 10.4, this bump in the backend package will allow both to use 10.4

Bring up ts-node

---

packages/prop-house-protocol/contracts/starknet/src/common/utils/merkle.cairo
packages/prop-house-protocol/contracts/starknet/src/test/merkle_test.cairo

This change ensures that `size` is rounded up when odd, correctly returning the ceiling value of `log2(leaf_count)`.

Fix `get_current_depth` Rounding Bug

---

packages/prop-house-webapp/package.json
packages/prop-house-webapp/src/components/ProposalCard/index.tsx
packages/prop-house-webapp/src/components/ProposalContent/index.tsx
packages/prop-house-webapp/src/components/RenderedProposalFields/index.tsx
packages/prop-house-webapp/src/utils/buildIpfsPath.ts
packages/prop-house-webapp/src/utils/ipfs.ts
packages/prop-house-webapp/tsconfig.json
yarn.lock

This PR refactors IPFS gateway rewriting and also takes advantage of Pinata's [image opimization](https://docs.pinata.cloud/docs/image-optimizations) to set a maximum image size. Currently set to the max breakpoint width of the proposal body (~930px). Images larger than this size will be shrunk by Pinata and cached.

Refactor ipfs rewrite, set image limit

---

packages/prop-house-webapp/src/components/InfRoundVotingControls/index.tsx
packages/prop-house-webapp/src/components/ProposalCard/index.tsx

- Users were seeing only their own vote count during the voting state for inf round props
- This PR fixes it by displaying cumulative votes during voting for both voters and non-voters
Before:
After:

Fix inf round vote count

---

netlify.toml

As we launch the onchain version of the app to prod (prop.house), we're going to continue to host the offchain version as offchain.prop.house. 
This PR would allow the `offchain` branch to work as prod and thus grab the necessary host vars to point to the production endpoints as opposed to the current dev endpoints.

Use prod env vars for offchain branch

---

packages/prop-house-webapp/src/components/RoundAwardsDisplay/index.tsx

SDK is returning awards in the wrong order where there are 10 or more awards. Indexes are displaying as:
0, 1, 10, 11, etc.., 2, 3, 4, 5

Fix awards ordering
